import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_Bengali } from 'next/font/google';

const noto = Noto_Sans_Bengali({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Evvent',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={noto.className}>{children}</body>
		</html>
	);
}
